import type { WorkspaceController } from '../hooks/useWorkspace';
export type TerminalPanelModel = Pick<
  WorkspaceController,
  | 'terminalVisible'
  | 'terminalFull'
  | 'resize'
  | 'resizeKey'
  | 'setTerminalHeight'
  | 'terminalPanel'
  | 'panes'
  | 'agentPreferences'
  | 'setAgentPreferences'
  | 'layout'
  | 'setLayout'
  | 'setMaxPane'
  | 'settings'
  | 'setSettings'
  | 'project'
  | 'setAgentMenu'
  | 'agentMenu'
  | 'addPane'
  | 'customPane'
  | 'setTerminalFull'
  | 'setTerminalVisible'
  | 'paneStates'
  | 'agentObservations'
  | 'agentUsage'
  | 'selectedPane'
  | 'focusAgent'
  | 'renameAgent'
  | 'restartAgent'
  | 'closePane'
  | 'maxPane'
  | 'paneState'
  | 'fail'
  | 'observeAgent'
  | 'updateAgentUsage'
  | 'runAgentCommand'
  | 'updateTerminalTitle'
  | 'paneFocus'
  | 'setSelectedPane'
  | 'git'
>;
